#! python3

"""
Automatically spins the 2048 game

"""

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

# TODO Click retry when the box comes up.

browser = webdriver.Firefox(executable_path="C:\Python27\geckodriver.exe")

site = "https://play2048.co/"

req = browser.get(site)
time.sleep(2)
reset = browser.find_element_by_class_name("restart-button")
reset.click()

time.sleep(1)

game = browser.find_element_by_tag_name("html")

def element_exists():
    try:
        browser.find_element_by_class_name("retry-button")
    except NoSuchElementException:
        return False
    return True

for revolution in range(100):
    game.send_keys(Keys.UP)
    game.send_keys(Keys.RIGHT)
    game.send_keys(Keys.DOWN)
    game.send_keys(Keys.LEFT)

    # if element_exists() = True:
    #     break

